dc_dict={"2":"pDC",
        "8":"pDC",
        "12":"pDC",
        "7":"cDC1",
        "0":"cDC2",
        "1":"cDC2",
        "3":"cDC2",
        "4":"cDC2",
        "6":"cDC2",
        "5":"cDC2",
        "9":"cDC2",
        "10":"cDC2",
        "11":"cDC2"}


mono_dict={"0":"CD14",
        "1":"CD14",
        "2":"CD14",
        "3":"CD14",
        "6":"CD14",
        "7":"CD14",
        "8":"CD14",
        "9":"CD14",
        "12":"CD14",
        "5":"Intermed",
        "4":"CD16",
        "10":"CD16",
        "11":"CD16"}

bc_dict={"1":"Naive",
        "2":"Naive",
        "3":"Naive",
        "9":"Naive",
        "10":"Naive",
        "11":"Naive",
        "12":"Naive",
        "13":"Naive",
        "0":"Memory",
        "4":"Memory",
        "5":"Memory",
        "7":"Memory",
        "15":"Memory",
        "16":"Memory",
        "6":"ASC",
        "14":"ASC",
        "8":"ABC"}

nk_dict={"1":"NK2",
        "4":"NK2",
        "5":"NK2",
        "8":"NK2",
        "9":"NK2",
        "10":"NK2",
        "7":"NK1",
        "0":"NK3",
        "2":"NK3",
        "3":"NK3",
        "6":"NK3"}

tc_dict={"0":"CD4",
        "1":"CD4",
        "5":"CD4",
        "9":"CD4",
        "10":"CD4",
        "CD4":"CD4",
        "2":"CD8",
        "3":"CD8",
        "4":"CD8",
        "6":"CD8",
        "12":"CD8",
        "CD8":"CD8",
        "7":"CD4-CD8-",
        "8":"CD4+CD8+",
        "11":"T-mito",
        "13":"T-mito",
        "T-mito":"T-mito"}

cd4_dict={"0":"CD4 Naive",
        "3":"CD4 Tcm",
        "1":"CD4 Tem",
        "2":"CD4 Tem",
        "4":"CD4 Tem",
        "7":"CD4 Tem",
        "8":"CD4 Tem",
        "9":"CD4 Tem",
        "5":"CD4 Treg",
        "6":"CD4 Tex"}

cd8_dict={"1":"CD8 Naive",
        "2":"CD8 Naive",
        "7":"CD8 Naive",
        "8":"CD8 Naive",
        "Naive":"CD8 Naive",
        "0":"CD8 Tem",
        "9":"CD8 Tem",
        "10":"CD8 Tem",
        "12":"CD8 Tem",
        "13":"CD8 Tem",
        "14":"CD8 Tem",
        "15":"CD8 Tem",
        "16":"CD8 Tem",
        "17":"CD8 Tem",
        "3":"CD8 CTL",
        "5":"CD8 CTL",
        "11":"CD8 CTL",
        "CTL":"CD8 CTL",
        "4":"CD8 Tex",
        "6":"CD8 Tex"}

